services:
  mongodb:
    image: mongo
    container_name: mongodb_insight
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootinsight
      MONGO_INITDB_ROOT_PASSWORD: rootinsight
      MONGO_USERNAME: insightuser
      MONGO_PASSWORD: insightpassword
      MONGO_INITDB_DATABASE: insight
    volumes:
      - ./backend/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - insight-backend-network

  mongo-express:
    image: mongo-express
    container_name: mongodb_express_insight
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_insight
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootinsight
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootinsight
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - insight-backend-network

  backend:
    image: insight-backend
    container_name: insight_backend
    build: ./backend
    environment:
      JWT_SECRET: insightsecret
      MONGODB_USERNAME: insightuser
      MONGODB_PASSWORD: insightpassword
      MONGODB_HOST: mongodb_insight
      MONGODB_PORT: 27017
      MONGODB_DATABASE: insight
      PORT: 8080
      JAR_FILE: ./target/SupplierApplicationInsight-1.0.0.jar
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - mongodb
    networks:
      - insight-backend-network

networks:
  insight-backend-network:
    driver: bridge
