services:
  mongodb:
    image: mongo
    container_name: mongodb_insight
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootinsight
      MONGO_INITDB_ROOT_PASSWORD: rootinsight
      MONGO_USERNAME: insightuser
      MONGO_PASSWORD: insightpassword
      MONGO_INITDB_DATABASE: insight
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      - insight-backend-network

  mongo-express:
    image: mongo-express
    container_name: mongodb_express_insight
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_insight
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootinsight
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootinsight
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

    depends_on:
      - mongodb
    ports:
      - "8888:8081"
    networks:
      - insight-backend-network

networks:
    insight-backend-network:
        driver: bridge
