services:
  mongodb:
    image: mongo:8.0-rc-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootinsight
      MONGO_INITDB_ROOT_PASSWORD: rootinsight
      MONGO_USERNAME: insightuser
      MONGO_PASSWORD: insightpassword
      MONGO_INITDB_DATABASE: insight
    volumes:
      - ./backend/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - insight-network

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootinsight
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootinsight
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - insight-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: insightsecret
      MONGODB_USERNAME: insightuser
      MONGODB_PASSWORD: insightpassword
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: insight
      PORT: 8080
      JAR_FILE: ./target/SupplierApplicationInsight-1.0.0.jar
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - mongodb
    networks:
      - insight-network

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFront
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - backend
    networks:
      - insight-network

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx_default.conf:/etc/nginx/nginx.conf alterar para o arquivo de configuração do nginx.conf em modo produção
#      - ./certificates:/etc/nginx/certificates
#    networks:
#      - insight-network
#    depends_on:
#      - frontend
#      - backend

networks:
  insight-network:
    driver: bridge